In [311]:
from iapws import IAPWS97
import numpy as np
import math

## Static Model Equations


### A. Hydraulic model of single pipe

By law of momentum conservation , hydraulic model can be written as:
$$ C_p = \frac {D^{5} \; \rho_m }{1.25 \times 10^{8} \lambda \; q \; P_1 \; (1+\eta) \; L}  $$

Equation for solving frictional factor $\lambda$:
$$ \lambda = 0.11 \times (\frac{\Delta}{D}+\frac{68}{Re})^{0.25} $$

Reynolds number is written as:
$$ Re = \frac {D \; u \; \rho_m}{\mu} = 354 \frac{q}{D \; \mu}$$

Where:
* $P_1$ - the input pressure of the steam in the pipe, Mpa;
* $\lambda$ - frictional factor
* $q$ - mass flow rate, tph;
* $D$ - the inner diameter of the pipe, mm;
* $L$ - length of the pipe, mm;
* $\rho_m$ - weighted mean density in the pipe, $kg/m^{3}$
* $\eta$ - equivalent length coefficient
* $\Delta$ - equivalent absolute roughness, mm;
* $Re$ - Reynolds number of the steam in the pipe;
* $u$ - characteristic velocity of the steam in the pipe, m/s
* $\mu$ - the mean dynamic viscosity coefficient, Pa*s or kg/(m s)

### B. Thermal model of a single pipe

By law of energy conservation, the static thermal model can be written as follows:

$$ C_T = \frac{278 \; c_p \; q^{2}} {(1+\beta \,) \; q_1 \; L} $$

The amount of heatloss along unit pipe length can be calculated using:

$$ q_l = \frac {T_0 - T_a}
    {\frac{1}{2 \pi \epsilon} \; ln\frac{D_o}{D_i} \; + \frac{1}{\pi \, D_o \, a_w}} $$
    
$a_w$ is determined by:
    $$ a_w = 11.6 + 7 \sqrt {v} $$

In [312]:
"""Hydraulic Model Functions"""
def dviscosity(P):
    """get dynamic viscosity from IAPWS given Pressure (Mpa)"""
    sat_steam=IAPWS97(P=P,x=1)  #saturated steam with known P
    return sat_steam.mu

def sp_heat (T):
    """return specific isobaric heat capacity (Cp); kJ/kg*K"""
    sat_steam=IAPWS97(T=T, x=1)  #saturated steam with known T in Kelvin
    return sat_steam.cp 

def nRe (q, D, mu):
    """Calculate reynolds number"""
    return 353*q/(D * mu)

def ffactor (delta, D, Re):
    """Calculate frictional factor"""
    return 0.11 * ((delta/D)+(68/Re))**0.25

def C_P(D, rho, friction, q, P, eta, L):
    """Calculate from hydraulic model"""
    c_p = D**5 * rho/(1.25*10**8* friction * q * P * (1+ eta) * L ) 
    return c_p

def aw (v):
    #calculate aw given air velocity; m/s
    return 11.6 + 7*v**0.5
#print ("aw = ", aw(1.11))

def heat_loss (To, Ta, epsilon, Do, Di, aw):
    num = To-Ta
    d1 = np.log(Do/Di)/(2*epsilon*math.pi)
    d2 = 1/(math.pi*(Do)*aw)
    #print (num, d1, d2)
    return (num / (d1 + d2))

def mass_flow (beta, heat_l, L, sp_heat, deltaT):
    return ((1+beta)*heat_l*L)/(278*sp_heat*deltaT)
    
#print (heat_loss(200+273.15, 32+273.15, 0.035, 920, 700, 19))

In [313]:
"""Initialize parameter values"""
eta = 0.2
delta = 0.2
beta = 0.15
epsilon = 0.035
error = 0.3

In [314]:
"""Pipe Specifications"""
#array of pipe lengths
L = np.array([600, 2300, 700, 1300, 1200])
Di = np.array([700., 600., 400., 500., 600])
Do = np.array([720, 630, 426, 529, 630])
insulation = np.array([110, 105, 95, 100, 105])
Do_insul = Do + insulation*2 #Outer diameer of pipe + 2*insulation thickness
#print (Do_insul)

"""Given Measured Data"""
#Define Q preliminary field; flow rate of the ith node
Q = np.array([-117.0, 19.0, 19.0, 79.0, 0.0, 0.0])

#Measured pressure data at nodes 1, 2, 3 and 4; initial guess for node 5 and 6
P = np.array([0.705, 0.679, 0.563, 0.445])
P5 = 0.5*(P[0]+P[1])             #P5 = 0.5*(P1+P2)             initial guess
mx = 0.5*(max(P[2], P[3])+P5)    #P6 = 0.5*( max(P3,P4) + P5)  initial guess
P = np.append(P, [P5,mx])
P2 = P**2

#Measured temp data at nodes 1, 2, 3 and 4; initial guess for node 5 and 6
T = np.array([286+273.15, 195+273.15, 246+273.15, 256+273.15])
mx = max(T[2], T[3])+.1     #P6 = max(P3,P4) initial guess
T = np.append(T, [T[0]-.1,mx]) #P5 = P1 initial guess
#print ("temp at nodes:", T)

#Delta T for each pipe segment
dT = np.array([T[0]-T[4], T[4]-T[1], T[5]-T[2], T[5]-T[3], T[4]-T[5]])
print (dT)

#create array of isobaric specific heat at pipeline
def get_cp (T):
    cp = np.array([sp_heat(T[0]), sp_heat(T[4]), sp_heat(T[5]), sp_heat(T[5]), sp_heat(T[4])])
    return cp
cp = get_cp(T)
           
#cp = np.array([sp_heat(T[0]), sp_heat(T[4]), sp_heat(T[5]), sp_heat(T[5]), sp_heat(T[4])])
#print (cp)


#for heat loss (q_l) calculation, set Ta at inlet temp
#Temperature of pipeline
Ta = np.array([T[0], T[4], T[5], T[5], T[4],])
#print ("temp at pipes:", Ta)

#define atmospheric temp
Tatm = 305.15


aw1 = aw(1.11111)


[  0.1  90.9  10.1   0.1  29.8]


In [315]:
"""Step 1: Calculate heat_loss (W/m)"""
#calculate heat loss vector along pipe (W/m)
q_l = heat_loss(Tatm, Ta, epsilon, Do_insul, Di, aw1)
#print (q_l)
#calculate mass flow vector along pipe
q_f = mass_flow(beta, q_l, L, cp, dT)
#print (q_f)

#test q vector; flow rate of each pipe
q = (1+beta)*q_l* L / (278 * cp * dT)
print (dT)
print ("q = ",q)

Aq = np.dot(A,q)
print (Aq)
print(Q)
obj = Aq + Q
print (obj)
np.sum(obj)

#def mass_flow (beta, heat_l, L, sp_heat, deltaT):
#    return ((1+beta)*heat_l*L)/(278*sp_heat*deltaT)

[  0.1  90.9  10.1   0.1  29.8]
q =  [ -876.91289674    -3.24187939    -7.81478843 -1678.54158973    -5.15938436]
[[ -876.91289674     3.24187939     7.81478843  1678.54158973
    868.51163298 -1681.19699379]]
[-117.   19.   19.   79.    0.    0.]
[[ -993.91289674    22.24187939    26.81478843  1757.54158973
    868.51163298 -1681.19699379]]


0.0

In [316]:
"""Hydraulic Calculation"""
#Calculate Reynolds Number
def dviscosity(P):
    """get dynamic viscosity from IAPWS given Pressure (Mpa)"""
    sat_steam=IAPWS97(P=P,x=1)  #saturated steam with known P
    return sat_steam.mu

def density(P):
    """get dynamic viscosity from IAPWS given Pressure (Mpa)"""
    sat_steam=IAPWS97(P=P,x=1)  #saturated steam with known P
    return sat_steam.rho   

def nRe (q, D, mu):
    """Calculate reynolds number"""
    return 354*q/(D * mu)

#Calculate dynamic viscosity coefficient os a function of pressure
#Line Pressure is the average of inlet and outlet pressure
mu = np.array([dviscosity((P[0]+P[4])/2), dviscosity((P[1]+P[4])/2), dviscosity((P[2]+P[5])/2), \
               dviscosity((P[3]+P[5])/2), dviscosity((P[4]+P[5])/2)])

#Calculate Renolds Number
Re = nRe (np.absolute(q_f), Di, mu)
#print(Re)

#Calculate Friction Factor
friction = ffactor(delta, Di, Re)

#Calculate mean density in the pipe
rho_m = np.array([density((P[0]+P[4])/2), density((P[1]+P[4])/2), density((P[2]+P[5])/2), \
               density((P[3]+P[5])/2), density((P[4]+P[5])/2)])

#array for inlet pressure of pipes
P_in = np.array([P[0], P[4], P[5], P[5], P[4]])

#Calculate Cp; pressure loss
print (Di**5 * rho_m/(1.25*10**8*L*P_in*friction*q_f*(1+eta)))



CP = C_P(Di, rho_m, friction, np.absolute(q_f), P_in, eta, L)

print (CP)
#CP = cp(Di, rho_m, friction, q_f, P_in, eta, L)
#print (CP)

At = np.transpose(A)

AtP = np.dot(At, P2)
AtP - np.array(AtP)
atp_only = AtP[[0],[0, 1, 2, 3, 4]]
print (len(AtP), AtP)
#print (CP, atp_only)

ar_atp = np.array(AtP)
ar_atp = ar_atp[[0],[0, 1, 2, 3, 4]]

q = CP*ar_atp
print ("q sum  ", q)

Aq = np.dot(A, q)
print (A, q)
np.sum(Aq)

[  -771.28929818 -19244.07979205  -3574.82756455    -27.86084814
 -23835.60396672]
[   771.28929818  19244.07979205   3574.82756455     27.86084814
  23835.60396672]
1 [[ 0.018161    0.017823    0.07678725  0.19573125  0.08510775]]
q sum   [   14.00738494   342.98723413   274.50117791     5.45323863  2028.5946235 ]
[[ 1  0  0  0  0]
 [ 0 -1  0  0  0]
 [ 0  0 -1  0  0]
 [ 0  0  0 -1  0]
 [-1  1  0  0  1]
 [ 0  0  1  1 -1]] [   14.00738494   342.98723413   274.50117791     5.45323863  2028.5946235 ]


2.2737367544323206e-13

In [324]:
"""Thermal Model"""

CT = 278 * cp * q**2 / ( (1+beta) * q_l * L)

AtT = np.dot(At, T)
ar_att = np.array(AtT)
ar_att = ar_att[[0],[0, 1, 2, 3, 4]]

q = CT * ar_att
print (q, CT, ar_att)

Aq = np.dot (A, q)
print ("Aq: ", Aq)
np.sum(Aq)

#print ("ACT:AtT", AtT, ar_att)

#print (CT, q)

[ -7.23873892e-167  -2.24717885e+006  -3.53097688e-007  -4.23678540e-146
  -1.27741895e+019] [ -7.23873892e-166  -2.47214395e+004  -3.49601671e-008  -4.23678540e-145
  -4.28664078e+017] [  0.1  90.9  10.1   0.1  29.8]
Aq:  [[ -7.23873892e-167   2.24717885e+006   3.53097688e-007   4.23678540e-146
   -1.27741895e+019   1.27741895e+019]]


0.0

## Flow chart of flow rate calculation

<iiimg src="images\flow_chart.png" ,width=700,height=1400>

## Determine matrix "A" and Q



In [318]:
"""Define matrix A based on given steam pipeline network"""
A = np.matrix('1, 0, 0, 0, 0; \
               0, -1, 0, 0, 0; \
               0, 0, -1, 0, 0; \
               0, 0, 0, -1, 0; \
               -1, 1, 0, 0, 1; \
               0, 0, 1, 1, -1')
q = np.array([2, 4, 6, 8, 10])

np.dot(A, q)

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = a + b
np.add(a, b)
#print (c)
np.sum(c)

66

### Reference

Luo, X., Yuan, M., Wang, H., Jia, Y., & Wu, F. (2012). On Steam Pipe Network Modeling and Flow Rate Calculation. Procedia Engineering, 29, 1897-1903.